### ISSUE TITLE
grunt build fails with defaults

### ISSUE THREAD

**Issue by mc007** [bryanforbes/generator-dojo#15]
just installed all with defaults and did run grunt build directly afterwards, build-report.txt 
says : 
error(313) Failed to optimize CSS file.
	file: /PMaster/test/dtest/src/dtest1/resources/main.css; error: TypeError: Cannot call method 'indexOf' of undefined

and console outputs just 

Warning: Task "dojo:dist" failed. Use --force to continue.

Aborted due to warnings.

**Comment by kfranqueiro** [comment]
Would you be able to post a gist of your main.css file?  Is this same file not failing under a normal build outside of generator-dojo?

**Comment by mc007** [comment]
hi, i didn't touch anything, just created the yo dojo app and run grunt build, so the content is:

@import "../../dijit/themes/claro/claro.css";
@import "../../dgrid/css/skins/claro.css";

**Comment by neonstalwart** [comment]
@mc007 that doesn't seem consistent with your error output.  where did dtest1 come from?

**Comment by mc007** [comment]
from #yo dojo dtest1 (used all defaults). 

however, did re-created/-re-run it again and grunt build doesn't throw this error anymore. welcome to node npm magic  sh*

**Comment by neonstalwart** [comment]
i also just tried this with no errors

```sh
npm install -g yo generator-dojo grunt-cli
mdkir dtest1
cd dtest1
yo dojo dtest1
grunt build
```

**Comment by mc007** [comment]
well, happy building then. no idea how this came.
