### ISSUE TITLE
The grunt server task has stylus hardcoded

### ISSUE THREAD

**Issue by hlavacek** [bryanforbes/generator-dojo#3]
Hello,

the grunt server task has stylus:compile and watch:stylus as nonconditional dependencies:

``` javascript
grunt.task.run([
    'stylus:compile',
    'connect:test',
    'watch:stylus'
]);
```

So if I choose not to include stylus in my build, when running the generator, the grunt server task will fail:

```
$ grunt server
Running "server" task
Warning: Task "stylus:compile" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by bryanforbes** [comment]
Thanks for the report! This was a complete oversight on my part. I've pushed a fix to master and will most likely release an updated version in the next few days. For now, you can clone the repo and use `npm link` or remove `'stylus:compile'` and `'watch:stylus'` from the generated `Gruntfile.js` and change `'connect:test'` to `'connect:test:keepalive'`.
